@@ .. @@
 import type { Metadata } from 'next'
 import { Inter } from 'next/font/google'
 import './globals.css'
+import { AuthProvider } from '@/lib/auth-context'
+import { AuthModalProvider } from '@/lib/auth-modal-context'
+import { AuthModal } from '@/components/auth-modal'
 
 const inter = Inter({ subsets: ['latin'] })
 
 export const metadata: Metadata = {
-  title: 'Create Next App',
-  description: 'Generated by create next app',
+  title: 'abdou - Caméra avec Filtres IA',
+  description: 'Application de caméra avec filtres IA avancés',
+  manifest: '/manifest.json',
+  themeColor: '#6366f1',
+  viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
 }
 
 export default function RootLayout({
@@ -17,7 +24,13 @@ export default function RootLayout({
 }) {
   return (
     <html lang="en">
-      <body className={inter.className}>{children}</body>
+      <body className={inter.className}>
+        <AuthProvider>
+          <AuthModalProvider>
+            {children}
+            <AuthModal />
+          </AuthModalProvider>
+        </AuthProvider>
+      </body>
     </html>
   )
 }